/**
 * Deterministic colour for each actor in a script.
 *
 * Colours are derived from the actor name, so nothing has to be stored in the
 * script data. Within one script every actor gets a different colour: the name
 * alone cannot guarantee that, because uniqueness needs to know the whole cast,
 * so the assignment is computed per script from the cast that is already in the
 * parsed JSON.
 *
 * Adding a role to a script keeps roughly 98% of the existing colours, because
 * the palette is a fixed 48 slots and each actor's preference order depends
 * only on its own name. A role is only displaced when a newcomer wants the
 * exact slot it holds.
 *
 * The palette itself is generated by scripts/gen-actor-palette.mjs. Every
 * colour clears WCAG AA on every background the app uses, in both themes, and
 * the set stays distinguishable under red-green colour vision deficiency. See
 * that script for the reasoning.
 */

// Generated by scripts/gen-actor-palette.mjs - do not edit by hand.
// Each entry is [light mode, dark mode].
const PALETTE = [
  ['oklch(0.3 0.07 60)', 'oklch(0.66 0.06 60)'],
  ['oklch(0.52 0.155 252)', 'oklch(0.89 0.055 252)'],
  ['oklch(0.52 0.105 96)', 'oklch(0.89 0.18 96)'],
  ['oklch(0.316 0.22 264)', 'oklch(0.676 0.17 264)'],
  ['oklch(0.379 0.065 198)', 'oklch(0.742 0.125 198)'],
  ['oklch(0.41 0.09 108)', 'oklch(0.775 0.165 108)'],
  ['oklch(0.457 0.085 174)', 'oklch(0.824 0.155 174)'],
  ['oklch(0.441 0.235 294)', 'oklch(0.808 0.105 294)'],
  ['oklch(0.3 0.055 222)', 'oklch(0.66 0.12 222)'],
  ['oklch(0.52 0.11 162)', 'oklch(0.89 0.18 162)'],
  ['oklch(0.347 0.165 324)', 'oklch(0.709 0.235 324)'],
  ['oklch(0.331 0.135 0)', 'oklch(0.693 0.215 0)'],
  ['oklch(0.457 0.185 30)', 'oklch(0.824 0.095 30)'],
  ['oklch(0.41 0.09 162)', 'oklch(0.775 0.17 162)'],
  ['oklch(0.504 0.21 348)', 'oklch(0.874 0.08 348)'],
  ['oklch(0.394 0.21 300)', 'oklch(0.759 0.145 300)'],
  ['oklch(0.441 0.12 150)', 'oklch(0.808 0.22 150)'],
  ['oklch(0.441 0.195 336)', 'oklch(0.808 0.155 336)'],
  ['oklch(0.3 0.055 174)', 'oklch(0.66 0.125 174)'],
  ['oklch(0.504 0.14 150)', 'oklch(0.874 0.235 150)'],
  ['oklch(0.331 0.15 336)', 'oklch(0.693 0.235 336)'],
  ['oklch(0.331 0.135 18)', 'oklch(0.693 0.195 18)'],
  ['oklch(0.473 0.235 276)', 'oklch(0.841 0.075 276)'],
  ['oklch(0.3 0.175 288)', 'oklch(0.66 0.055 288)'],
  ['oklch(0.426 0.075 186)', 'oklch(0.791 0.135 186)'],
  ['oklch(0.363 0.11 42)', 'oklch(0.726 0.175 42)'],
  ['oklch(0.394 0.175 336)', 'oklch(0.759 0.21 336)'],
  ['oklch(0.489 0.095 168)', 'oklch(0.857 0.17 168)'],
  ['oklch(0.379 0.09 156)', 'oklch(0.742 0.18 156)'],
  ['oklch(0.347 0.06 192)', 'oklch(0.709 0.12 192)'],
  ['oklch(0.473 0.08 192)', 'oklch(0.841 0.14 192)'],
  ['oklch(0.473 0.13 150)', 'oklch(0.841 0.23 150)'],
  ['oklch(0.441 0.11 126)', 'oklch(0.808 0.205 126)'],
  ['oklch(0.316 0.075 240)', 'oklch(0.676 0.155 240)'],
  ['oklch(0.41 0.11 150)', 'oklch(0.775 0.21 150)'],
  ['oklch(0.489 0.22 330)', 'oklch(0.857 0.125 330)'],
  ['oklch(0.394 0.075 174)', 'oklch(0.759 0.14 174)'],
  ['oklch(0.363 0.16 336)', 'oklch(0.726 0.235 336)'],
  ['oklch(0.441 0.095 162)', 'oklch(0.808 0.175 162)'],
  ['oklch(0.363 0.15 354)', 'oklch(0.726 0.195 354)'],
  ['oklch(0.489 0.115 156)', 'oklch(0.857 0.205 156)'],
  ['oklch(0.316 0.055 192)', 'oklch(0.676 0.115 192)'],
  ['oklch(0.441 0.185 348)', 'oklch(0.808 0.13 348)'],
  ['oklch(0.347 0.175 312)', 'oklch(0.709 0.21 312)'],
  ['oklch(0.316 0.07 162)', 'oklch(0.676 0.145 162)'],
  ['oklch(0.52 0.205 18)', 'oklch(0.89 0.055 18)'],
  ['oklch(0.379 0.085 240)', 'oklch(0.742 0.145 240)'],
  ['oklch(0.41 0.195 324)', 'oklch(0.775 0.205 324)']
];

const SLOTS = PALETTE.length;

/** True for the pseudo-actor that stands in for unattributed stage directions. */
function isStageDirections(actor) {
  return !actor || actor === 'undefined';
}

/** FNV-1a. Small, dependency free, and it avalanches: "Тевье" and "Тевья" land far apart. */
function hash(text, seed) {
  let h = seed >>> 0;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/**
 * The order this actor would like to claim palette slots in.
 * Derived only from the name, so it never shifts when the cast changes.
 */
function preferences(actor) {
  let state = hash(actor, 0x811c9dc5) || 1;
  const random = () => {
    // xorshift32, seeded from the name
    state ^= state << 13; state >>>= 0;
    state ^= state >> 17;
    state ^= state << 5; state >>>= 0;
    return state / 0x100000000;
  };
  const order = Array.from({ length: SLOTS }, (_, i) => i);
  for (let i = SLOTS - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [order[i], order[j]] = [order[j], order[i]];
  }
  return order;
}

/**
 * Give every actor its own palette slot.
 *
 * Actors are processed in hash order rather than alphabetically or by line
 * count, both of which would reshuffle when the script is edited. Each takes
 * the first slot it prefers that is still free.
 *
 * Casts larger than the palette are not realistic today (the largest script has
 * 41 actors) but are handled by letting the overflow share colours rather than
 * throwing.
 */
export function assignActorColors(actors) {
  const cast = actors.filter(a => !isStageDirections(a));
  const order = [...cast].sort((a, b) => hash(a, 7) - hash(b, 7) || (a < b ? -1 : 1));

  const taken = new Array(SLOTS).fill(false);
  const colors = {};

  for (const actor of order) {
    const wanted = preferences(actor);
    let slot = wanted.find(i => !taken[i]);
    if (slot === undefined) slot = wanted[0]; // cast exceeds the palette
    taken[slot] = true;
    colors[actor] = { light: PALETTE[slot][0], dark: PALETTE[slot][1] };
  }

  return colors;
}

/** Every distinct actor in a parsed script, stage directions excluded. */
export function castOf(script) {
  const cast = new Set();
  for (const act of script?.acts || []) {
    for (const scene of act.scenes || []) {
      for (const line of scene.lines || []) {
        if (!isStageDirections(line.actor)) cast.add(line.actor);
      }
    }
  }
  return [...cast];
}

const cache = new Map();

/**
 * Colours for a whole script, memoised.
 *
 * The largest script renders several thousand lines, so this must not be
 * recomputed per line. Keyed on the cast so an edited script recolours.
 */
export function actorColorsForScript(script) {
  const cast = castOf(script);
  if (cast.length === 0) return {};
  const key = [...cast].sort().join('\u0000');
  let colors = cache.get(key);
  if (!colors) {
    colors = assignActorColors(cast);
    cache.set(key, colors);
  }
  return colors;
}
