/**
 * Colour per actor, assigned by cast rank.
 *
 * Roles are ranked by how many lines they speak, and rank picks the palette
 * entry: the busiest role takes the first colour, the next takes the second,
 * and so on. The palette is ordered so that every prefix is the best palette
 * of that size, which means the characters on stage most often are the ones
 * given the most clearly different colours, and near-duplicates only ever
 * reach walk-on parts.
 *
 * An earlier version derived the colour from a hash of the name. That kept
 * colours stable when a role was added, but it scattered a small cast across
 * the whole palette, so a twelve-role play could draw two neighbouring
 * desaturated teals and the two leads became impossible to tell apart. Rank
 * trades that stability away, deliberately: colours may shuffle when a script
 * is edited, and a role pinned through the picker keeps its colour regardless
 * because overrides are stored against the name.
 *
 * The palette is generated by scripts/gen-actor-palette.mjs. Every colour
 * clears WCAG AA on every background the app uses in both themes, and the set
 * stays separable under red-green colour vision deficiency. See that script
 * for the reasoning.
 */

// Generated by scripts/gen-actor-palette.mjs - do not edit by hand.
// Each entry is [light mode, dark mode].
const PALETTE = [
  ['oklch(0.296 0.07 120)', 'oklch(0.656 0.155 120)'],
  ['oklch(0.345 0.23 267)', 'oklch(0.705 0.15 267)'],
  ['oklch(0.378 0.165 336)', 'oklch(0.738 0.235 336)'],
  ['oklch(0.508 0.205 30)', 'oklch(0.868 0.07 30)'],
  ['oklch(0.524 0.09 213)', 'oklch(0.884 0.095 213)'],
  ['oklch(0.329 0.1 42)', 'oklch(0.689 0.205 42)'],
  ['oklch(0.491 0.235 312)', 'oklch(0.851 0.1 312)'],
  ['oklch(0.508 0.165 144)', 'oklch(0.868 0.235 144)'],
  ['oklch(0.394 0.16 6)', 'oklch(0.754 0.155 6)'],
  ['oklch(0.491 0.1 168)', 'oklch(0.851 0.17 168)'],
  ['oklch(0.54 0.11 81)', 'oklch(0.9 0.095 81)'],
  ['oklch(0.329 0.165 315)', 'oklch(0.689 0.2 315)'],
  ['oklch(0.491 0.205 351)', 'oklch(0.851 0.095 351)'],
  ['oklch(0.426 0.115 249)', 'oklch(0.786 0.11 249)'],
  ['oklch(0.394 0.22 291)', 'oklch(0.754 0.135 291)'],
  ['oklch(0.475 0.125 129)', 'oklch(0.835 0.22 129)'],
  ['oklch(0.41 0.15 33)', 'oklch(0.77 0.135 33)'],
  ['oklch(0.475 0.215 333)', 'oklch(0.835 0.14 333)'],
  ['oklch(0.361 0.19 303)', 'oklch(0.721 0.175 303)'],
  ['oklch(0.329 0.14 351)', 'oklch(0.689 0.18 351)'],
  ['oklch(0.378 0.065 186)', 'oklch(0.738 0.125 186)'],
  ['oklch(0.508 0.13 153)', 'oklch(0.868 0.22 153)'],
  ['oklch(0.361 0.075 90)', 'oklch(0.721 0.145 90)'],
  ['oklch(0.443 0.175 18)', 'oklch(0.802 0.11 18)'],
  ['oklch(0.313 0.065 234)', 'oklch(0.672 0.14 234)'],
  ['oklch(0.345 0.14 18)', 'oklch(0.705 0.185 18)'],
  ['oklch(0.313 0.175 291)', 'oklch(0.672 0.1 291)'],
  ['oklch(0.296 0.07 156)', 'oklch(0.656 0.155 156)'],
  ['oklch(0.443 0.1 63)', 'oklch(0.802 0.14 63)'],
  ['oklch(0.524 0.21 0)', 'oklch(0.884 0.065 0)'],
  ['oklch(0.459 0.22 321)', 'oklch(0.819 0.15 321)'],
  ['oklch(0.426 0.18 345)', 'oklch(0.786 0.155 345)'],
  ['oklch(0.313 0.15 324)', 'oklch(0.672 0.065 324)'],
  ['oklch(0.475 0.205 342)', 'oklch(0.835 0.12 342)'],
  ['oklch(0.329 0.135 3)', 'oklch(0.689 0.18 3)'],
  ['oklch(0.443 0.18 354)', 'oklch(0.802 0.125 354)'],
  ['oklch(0.378 0.095 153)', 'oklch(0.738 0.19 153)'],
  ['oklch(0.524 0.09 183)', 'oklch(0.884 0.155 183)'],
  ['oklch(0.54 0.235 327)', 'oklch(0.9 0.09 327)'],
  ['oklch(0.426 0.19 333)', 'oklch(0.786 0.19 333)'],
  ['oklch(0.459 0.185 3)', 'oklch(0.819 0.105 3)'],
  ['oklch(0.345 0.15 342)', 'oklch(0.705 0.235 342)'],
  ['oklch(0.394 0.16 357)', 'oklch(0.754 0.165 357)'],
  ['oklch(0.459 0.075 201)', 'oklch(0.819 0.135 201)'],
  ['oklch(0.41 0.07 216)', 'oklch(0.77 0.135 216)'],
  ['oklch(0.394 0.16 21)', 'oklch(0.754 0.145 21)'],
  ['oklch(0.361 0.07 171)', 'oklch(0.721 0.14 171)'],
  ['oklch(0.443 0.115 153)', 'oklch(0.802 0.205 153)']
];

const PALETTE_SIZE = PALETTE.length;

// Generated by scripts/gen-actor-palette.mjs - do not edit by hand.
// Hue-ordered ramp for the colour override picker.
const HUE_CHOICES = [
  ['oklch(0.565 0.23 0)', 'oklch(0.695 0.21 0)'],
  ['oklch(0.56 0.225 15)', 'oklch(0.69 0.2 15)'],
  ['oklch(0.56 0.225 30)', 'oklch(0.69 0.2 30)'],
  ['oklch(0.54 0.155 45)', 'oklch(0.7 0.2 45)'],
  ['oklch(0.53 0.125 60)', 'oklch(0.745 0.175 60)'],
  ['oklch(0.52 0.11 75)', 'oklch(0.805 0.17 75)'],
  ['oklch(0.535 0.11 90)', 'oklch(0.855 0.175 90)'],
  ['oklch(0.515 0.11 105)', 'oklch(0.92 0.195 105)'],
  ['oklch(0.525 0.125 120)', 'oklch(0.93 0.22 120)'],
  ['oklch(0.51 0.15 135)', 'oklch(0.805 0.235 135)'],
  ['oklch(0.505 0.14 150)', 'oklch(0.855 0.235 150)'],
  ['oklch(0.52 0.11 165)', 'oklch(0.88 0.185 165)'],
  ['oklch(0.52 0.095 180)', 'oklch(0.885 0.16 180)'],
  ['oklch(0.525 0.09 195)', 'oklch(0.88 0.15 195)'],
  ['oklch(0.52 0.09 210)', 'oklch(0.84 0.145 210)'],
  ['oklch(0.525 0.1 225)', 'oklch(0.765 0.145 225)'],
  ['oklch(0.52 0.12 240)', 'oklch(0.7 0.16 240)'],
  ['oklch(0.53 0.175 255)', 'oklch(0.67 0.175 255)'],
  ['oklch(0.355 0.235 270)', 'oklch(0.675 0.17 270)'],
  ['oklch(0.4 0.235 285)', 'oklch(0.68 0.175 285)'],
  ['oklch(0.44 0.235 300)', 'oklch(0.685 0.19 300)'],
  ['oklch(0.475 0.235 315)', 'oklch(0.695 0.235 315)'],
  ['oklch(0.515 0.235 330)', 'oklch(0.7 0.235 330)'],
  ['oklch(0.55 0.235 345)', 'oklch(0.7 0.235 345)']
];

/**
 * The colours offered by the override picker, in hue order.
 *
 * Deliberately not the palette. The palette is ordered so that every prefix is
 * well spread, which leaves its later entries looking like near duplicates of
 * earlier ones once they are laid out as a grid. Sorted by hue, neighbours are
 * meant to resemble each other and the set reads as a spectrum.
 */
export const hueChoices = () => HUE_CHOICES.map(([light, dark], index) => ({ index, light, dark }));

const paletteColor = (index) => {
  const [light, dark] = PALETTE[((index % PALETTE_SIZE) + PALETTE_SIZE) % PALETTE_SIZE];
  return { light, dark };
};

const hueColor = (index) => {
  const [light, dark] = HUE_CHOICES[((index % HUE_CHOICES.length) + HUE_CHOICES.length) % HUE_CHOICES.length];
  return { light, dark };
};

/** True for the pseudo-actor that stands in for unattributed stage directions. */
export function isStageDirections(actor) {
  return !actor || actor === 'undefined';
}

/**
 * Speaking roles in rank order: most lines first.
 *
 * Ties are broken by name, and by code unit rather than localeCompare, which
 * varies by locale and would make the colours depend on the device. Ties are
 * not an edge case; in the largest script most of the cast shares a line count
 * with somebody.
 */
export function rankedCast(script) {
  const counts = new Map();
  for (const act of script?.acts || []) {
    for (const scene of act.scenes || []) {
      for (const line of scene.lines || []) {
        if (isStageDirections(line.actor)) continue;
        counts.set(line.actor, (counts.get(line.actor) || 0) + 1);
      }
    }
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))
    .map(([actor]) => actor);
}

/**
 * Colours for a whole cast.
 *
 * `overrides` maps an actor name to an index into the picker ramp. Two roles
 * are allowed to end up with the same colour that way; it is a deliberate
 * choice by the user, not something to protect them from.
 *
 * `hueIndex` is the ramp entry in force, or null when the role still has the
 * colour its rank gives it, which is what the picker marks as selected.
 */
export function assignActorColors(ranked, overrides = {}) {
  const colors = {};
  ranked.forEach((actor, rank) => {
    const override = overrides[actor];
    const pinned = Number.isInteger(override);
    colors[actor] = {
      ...(pinned ? hueColor(override) : paletteColor(rank)),
      hueIndex: pinned ? ((override % HUE_CHOICES.length) + HUE_CHOICES.length) % HUE_CHOICES.length : null
    };
  });
  return colors;
}

const cache = new Map();

/**
 * Colours for a script, memoised.
 *
 * The largest script renders several thousand lines, so this must not run per
 * line. The key covers the cast order and the overrides, so both an edited
 * script and a newly picked colour recompute.
 */
export function actorColorsForScript(script, overrides = {}) {
  const ranked = rankedCast(script);
  if (ranked.length === 0) return {};
  const key = ranked.join('\u0000') + '\u0001' +
    Object.keys(overrides).sort().map(k => k + '=' + overrides[k]).join(',');
  let colors = cache.get(key);
  if (!colors) {
    colors = assignActorColors(ranked, overrides);
    cache.set(key, colors);
  }
  return colors;
}
